apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: {{ .Release.Name }}
spec:
  applicationImage: {{ .Release.Name }}:latest
  replicas: 1
  env:
    # Env vars to connect to PostgreSQL DB
    - name: POSTGRESQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: postgresql
    - name: POSTGRESQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: postgresql
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: postgresql
    - name: POSTGRESQL_DATASOURCE
      value: qs-ds
    - name: POSTGRESQL_SERVICE_HOST
      value: postgresql